spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookSocialNetwork?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: localhost
    port: 1025
    username: root
    password: root
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable:true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


application:
  security:
    jwt:
      secret-key: 1^%ru_rov#550jcliqmt_a8ueft)rk7ox-0)dunxi76a06wx9-
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account